# Generated by Django 5.1.4 on 2025-01-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutCliente', models.CharField(max_length=12)),
                ('nombreCliente', models.CharField(max_length=40)),
                ('nombreContacto1', models.CharField(max_length=40)),
                ('nombreContacto2', models.CharField(max_length=40, null=True)),
                ('cargoContacto1', models.CharField(max_length=20)),
                ('cargoContacto2', models.CharField(max_length=20, null=True)),
                ('numeroContacto1', models.IntegerField()),
                ('numeroContacto2', models.IntegerField(null=True)),
                ('correoContacto1', models.EmailField(max_length=254)),
                ('correoContacto2', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
