# Generated by Django 5.1.5 on 2025-01-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutCliente', models.CharField(max_length=12, unique=True)),
                ('nombreCliente', models.CharField(max_length=40)),
                ('nombreContacto1', models.CharField(max_length=40)),
                ('nombreContacto2', models.CharField(max_length=40, null=True)),
                ('cargoContacto1', models.CharField(max_length=20)),
                ('cargoContacto2', models.CharField(max_length=20, null=True)),
                ('numeroContacto1', models.IntegerField()),
                ('numeroContacto2', models.IntegerField(null=True)),
                ('correoContacto1', models.EmailField(max_length=254)),
                ('correoContacto2', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('codFactura', models.IntegerField(unique=True)),
                ('monto', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('LISTO', 'LISTO')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedorClientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaImportada',
            fields=[
                ('numDocumento', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('abonos', models.CharField(max_length=40)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedorClientes.factura')),
            ],
        ),
    ]
