# Generated by Django 5.1.5 on 2025-01-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaImportada',
            fields=[
                ('numDocumento', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('abonos', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutCliente',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='codFactura',
            field=models.IntegerField(unique=True),
        ),
    ]
