# Generated by Django 5.1.5 on 2025-01-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorClientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaimportada',
            name='factura',
        ),
    ]
