# Generated by Django 5.1.5 on 2025-01-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorClientes', '0002_facturaimportada_alter_cliente_rutcliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaimportada',
            name='fecha',
        ),
    ]
