# Generated by Django 5.1.5 on 2025-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorClientes', '0002_remove_facturaimportada_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaimportada',
            name='abonos',
            field=models.IntegerField(),
        ),
    ]
