# Generated by Django 5.1.4 on 2025-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorClientes', '0003_alter_facturaimportada_abonos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
